CREATE DATABASE universite_test;
USE universite_test;
SHOW TABLES;
SELECT COUNT(*) FROM ETUDIANT;
SELECT * 
INTO OUTFILE '/tmp/etudiants.csv'
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM ETUDIANT;
SELECT * 
INTO OUTFILE '/tmp/etudiants.csv'
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM ETUDIANT;
ALTER TABLE INSCRIPTION 
  ADD INDEX idx_date_inscr(date_inscription);
  ALTER TABLE INSCRIPTION 
  DROP INDEX idx_date_inscr;
  EXPLAIN
SELECT e.nom, COUNT(i.id)
FROM ETUDIANT e
JOIN INSCRIPTION i ON i.etudiant_id = e.id
GROUP BY e.id;
ANALYZE TABLE INSCRIPTION;
OPTIMIZE TABLE INSCRIPTION;